# Virtual Try-On Training Configuration
# Proprietary settings for optimal training performance

# Data Configuration
data:
  data_root: "data/datasets"
  train_pairs_file: "data/datasets/train_pairs.txt"
  test_pairs_file: "data/datasets/test_pairs.txt"
  image_size: [512, 384]
  use_augmentation: true
  pose_refinement_stages: 3

# Model Configuration
model:
  feature_dim: 256
  use_occlusion_awareness: true
  use_texture_synthesis: true
  use_quality_assessment: true
  num_control_points: 16
  max_garments: 3

# Training Configuration
training:
  batch_size: 8
  num_epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.0001
  max_grad_norm: 1.0
  
  # Scheduler Configuration
  scheduler_t0: 10
  scheduler_t_mult: 2
  
  # Loss Weights (Proprietary)
  loss_weights:
    reconstruction: 1.0
    perceptual: 0.1
    pose_consistency: 0.5
    anatomical: 0.3
    occlusion: 0.2
    texture: 0.4
    adversarial: 0.1

# Hardware Configuration
hardware:
  device: "cuda"
  num_workers: 4
  pin_memory: true
  mixed_precision: true

# Logging Configuration
logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  save_interval: 5
  log_interval: 100
  use_wandb: false
  project_name: "virtual-try-on"

# Validation Configuration
validation:
  val_interval: 1
  save_best_only: true
  early_stopping_patience: 10

# Real-time Configuration
real_time:
  use_model_compression: true
  use_adaptive_computation: true
  fast_mode_threshold: 0.5

# Patentable Features Configuration
patentable_features:
  # Multi-stage pose refinement
  pose_refinement_stages: 3
  pose_confidence_threshold: 0.3
  
  # Anatomical constraints
  anatomical_constraints_enabled: true
  joint_angle_penalty: 0.1
  limb_length_penalty: 0.1
  
  # Texture preservation
  texture_synthesis_enabled: true
  multi_scale_texture: true
  texture_preservation_weight: 0.4
  
  # Occlusion handling
  occlusion_awareness_enabled: true
  depth_estimation_enabled: true
  occlusion_smoothness_weight: 0.1
  
  # Quality assessment
  quality_assessment_enabled: true
  adaptive_refinement: true
  max_refinement_steps: 3

# Advanced Training Features
advanced:
  # Curriculum learning
  curriculum_learning: true
  pose_complexity_weighting: true
  
  # Progressive training
  progressive_training: true
  stage_epochs: [20, 30, 50]
  
  # Quality-aware sampling
  quality_aware_sampling: true
  sample_weighting: true
  
  # Multi-scale training
  multi_scale_training: true
  scale_factors: [0.5, 1.0, 2.0]

# Optimization Configuration
optimization:
  # Optimizer settings
  optimizer: "AdamW"
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  
  # Learning rate scheduling
  warmup_epochs: 5
  warmup_factor: 0.1
  
  # Gradient accumulation
  gradient_accumulation_steps: 1
  
  # Mixed precision
  fp16: true
  fp16_opt_level: "O1"

# Data Augmentation (Proprietary)
augmentation:
  # Geometric augmentations
  horizontal_flip: 0.5
  rotation_range: 10
  scale_range: [0.8, 1.2]
  translation_range: 0.1
  
  # Color augmentations
  brightness_contrast: 0.2
  hue_saturation: 0.1
  color_jitter: 0.3
  
  # Noise and blur
  gaussian_noise: 0.1
  motion_blur: 0.05
  gaussian_blur: 0.05
  
  # Elastic transformations
  elastic_transform: 0.1
  grid_distortion: 0.1
  optical_distortion: 0.1

# Evaluation Metrics
metrics:
  # Image quality metrics
  ssim: true
  lpips: true
  fid: true
  
  # Pose metrics
  pose_accuracy: true
  keypoint_distance: true
  
  # User satisfaction
  user_feedback: false
  feedback_threshold: 0.7

# Deployment Configuration
deployment:
  # Model compression
  quantization: true
  pruning: false
  distillation: false
  
  # Real-time optimization
  tensorrt: false
  onnx_export: true
  
  # Web deployment
  web_optimization: true
  progressive_loading: true
  cache_strategy: "lru"

# Security and Privacy
security:
  # Data privacy
  anonymize_data: true
  remove_metadata: true
  
  # Model protection
  model_encryption: false
  watermarking: true
  
  # Access control
  api_rate_limiting: true
  user_authentication: true 